//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelGeometry
    {
        public ModelGeometry()
        {
            this.ModelContours = new HashSet<ModelContour>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumVertices { get; set; }
        public Nullable<int> NumIndices { get; set; }
        public string VertexBuffer { get; set; }
        public string IndexBuffer { get; set; }
        public Nullable<double> MinX { get; set; }
        public Nullable<double> MinY { get; set; }
        public Nullable<double> MinZ { get; set; }
        public Nullable<double> MaxX { get; set; }
        public Nullable<double> MaxY { get; set; }
        public Nullable<double> MaxZ { get; set; }
    
        public virtual ICollection<ModelContour> ModelContours { get; set; }
    }
}
