//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelContour
    {
        public int Id { get; set; }
        public int ModelId { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumValues { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public string ValueBuffer { get; set; }
    
        public virtual ModelGeometry ModelGeometry { get; set; }
    }
}
