//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class web_femEntities : DbContext
    {
        public web_femEntities()
            : base("name=web_femEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ColorMap> ColorMaps { get; set; }
        public DbSet<ModelContour> ModelContours { get; set; }
        public DbSet<ModelGeometry> ModelGeometries { get; set; }
    }
}
